// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserVehicle = `-- name: AssignUserVehicle :one
INSERT INTO user_vehicles (user_id, vehicle_id)
VALUES ($1, $2)
RETURNING user_id, vehicle_id, created_at
`

type AssignUserVehicleParams struct {
	UserID    int64
	VehicleID string
}

func (q *Queries) AssignUserVehicle(ctx context.Context, arg AssignUserVehicleParams) (UserVehicle, error) {
	row := q.db.QueryRow(ctx, assignUserVehicle, arg.UserID, arg.VehicleID)
	var i UserVehicle
	err := row.Scan(&i.UserID, &i.VehicleID, &i.CreatedAt)
	return i, err
}

const checkUserVehicleAssignment = `-- name: CheckUserVehicleAssignment :one
SELECT user_id, vehicle_id
FROM user_vehicles
WHERE user_id = $1 AND vehicle_id = $2
`

type CheckUserVehicleAssignmentParams struct {
	UserID    int64
	VehicleID string
}

type CheckUserVehicleAssignmentRow struct {
	UserID    int64
	VehicleID string
}

func (q *Queries) CheckUserVehicleAssignment(ctx context.Context, arg CheckUserVehicleAssignmentParams) (CheckUserVehicleAssignmentRow, error) {
	row := q.db.QueryRow(ctx, checkUserVehicleAssignment, arg.UserID, arg.VehicleID)
	var i CheckUserVehicleAssignmentRow
	err := row.Scan(&i.UserID, &i.VehicleID)
	return i, err
}

const countActiveTrips = `-- name: CountActiveTrips :one
SELECT COUNT(*) FROM trips WHERE status = 'active'
`

func (q *Queries) CountActiveTrips(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTrips)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveUsersByRole = `-- name: CountActiveUsersByRole :one
SELECT COUNT(*) FROM users WHERE role = $1 AND active = true
`

func (q *Queries) CountActiveUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveVehicles = `-- name: CountActiveVehicles :one
SELECT COUNT(*) FROM vehicles WHERE active = true
`

func (q *Queries) CountActiveVehicles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveVehicles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM users WHERE role = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, role, active, created_at, updated_at
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash string
	Role         string
}

type CreateUserRow struct {
	ID        int64
	Name      string
	Email     string
	Role      string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVehicle = `-- name: CreateVehicle :execrows
INSERT INTO vehicles (id, label, agency_tag)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
`

type CreateVehicleParams struct {
	ID        string
	Label     string
	AgencyTag string
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (int64, error) {
	result, err := q.db.Exec(ctx, createVehicle, arg.ID, arg.Label, arg.AgencyTag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endTrip = `-- name: EndTrip :execrows
UPDATE trips
SET status = 'completed', end_time = NOW()
WHERE id = $1 AND user_id = $2 AND status = 'active'
`

type EndTripParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) EndTrip(ctx context.Context, arg EndTripParams) (int64, error) {
	result, err := q.db.Exec(ctx, endTrip, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveTripByUser = `-- name: GetActiveTripByUser :one
SELECT id, user_id, vehicle_id, route_id, gtfs_trip_id, start_time, end_time, status, created_at, updated_at
FROM trips
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveTripByUser(ctx context.Context, userID int64) (Trip, error) {
	row := q.db.QueryRow(ctx, getActiveTripByUser, userID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleID,
		&i.RouteID,
		&i.GtfsTripID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationHistory = `-- name: GetLocationHistory :many
SELECT latitude, longitude, bearing, speed, accuracy, timestamp, trip_id, received_at
FROM location_points
WHERE vehicle_id = $1
  AND timestamp >= $2
  AND timestamp <= $3
ORDER BY timestamp DESC
LIMIT $4
`

type GetLocationHistoryParams struct {
	VehicleID   string
	Timestamp   int64
	Timestamp_2 int64
	Limit       int32
}

type GetLocationHistoryRow struct {
	Latitude   float64
	Longitude  float64
	Bearing    pgtype.Float8
	Speed      pgtype.Float8
	Accuracy   pgtype.Float8
	Timestamp  int64
	TripID     string
	ReceivedAt pgtype.Timestamptz
}

func (q *Queries) GetLocationHistory(ctx context.Context, arg GetLocationHistoryParams) ([]GetLocationHistoryRow, error) {
	rows, err := q.db.Query(ctx, getLocationHistory,
		arg.VehicleID,
		arg.Timestamp,
		arg.Timestamp_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLocationHistoryRow
	for rows.Next() {
		var i GetLocationHistoryRow
		if err := rows.Scan(
			&i.Latitude,
			&i.Longitude,
			&i.Bearing,
			&i.Speed,
			&i.Accuracy,
			&i.Timestamp,
			&i.TripID,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentLocations = `-- name: GetRecentLocations :many
SELECT DISTINCT ON (vehicle_id)
    vehicle_id, trip_id, latitude, longitude, bearing, speed, accuracy, timestamp, driver_id
FROM location_points
WHERE received_at > $1
ORDER BY vehicle_id, received_at DESC
`

type GetRecentLocationsRow struct {
	VehicleID string
	TripID    string
	Latitude  float64
	Longitude float64
	Bearing   pgtype.Float8
	Speed     pgtype.Float8
	Accuracy  pgtype.Float8
	Timestamp int64
	DriverID  string
}

func (q *Queries) GetRecentLocations(ctx context.Context, receivedAt pgtype.Timestamptz) ([]GetRecentLocationsRow, error) {
	rows, err := q.db.Query(ctx, getRecentLocations, receivedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentLocationsRow
	for rows.Next() {
		var i GetRecentLocationsRow
		if err := rows.Scan(
			&i.VehicleID,
			&i.TripID,
			&i.Latitude,
			&i.Longitude,
			&i.Bearing,
			&i.Speed,
			&i.Accuracy,
			&i.Timestamp,
			&i.DriverID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripSummary = `-- name: GetTripSummary :one
SELECT t.id, t.vehicle_id, v.label AS vehicle_label, t.user_id, u.name AS driver_name,
       t.route_id, t.gtfs_trip_id, t.start_time, t.end_time, t.status
FROM trips t
JOIN users u ON u.id = t.user_id
JOIN vehicles v ON v.id = t.vehicle_id
WHERE t.id = $1
`

type GetTripSummaryRow struct {
	ID           int64
	VehicleID    string
	VehicleLabel string
	UserID       int64
	DriverName   string
	RouteID      string
	GtfsTripID   string
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	Status       string
}

func (q *Queries) GetTripSummary(ctx context.Context, id int64) (GetTripSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTripSummary, id)
	var i GetTripSummaryRow
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.VehicleLabel,
		&i.UserID,
		&i.DriverName,
		&i.RouteID,
		&i.GtfsTripID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, role, active, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        int64
	Name      string
	Email     string
	Role      string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleByID = `-- name: GetVehicleByID :one
SELECT id, label, agency_tag, active, created_at, updated_at
FROM vehicles
WHERE id = $1
`

type GetVehicleByIDRow struct {
	ID        string
	Label     string
	AgencyTag string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetVehicleByID(ctx context.Context, id string) (GetVehicleByIDRow, error) {
	row := q.db.QueryRow(ctx, getVehicleByID, id)
	var i GetVehicleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.AgencyTag,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLocationPoint = `-- name: InsertLocationPoint :exec
INSERT INTO location_points (vehicle_id, trip_id, latitude, longitude, bearing, speed, accuracy, timestamp, driver_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertLocationPointParams struct {
	VehicleID string
	TripID    string
	Latitude  float64
	Longitude float64
	Bearing   pgtype.Float8
	Speed     pgtype.Float8
	Accuracy  pgtype.Float8
	Timestamp int64
	DriverID  string
}

func (q *Queries) InsertLocationPoint(ctx context.Context, arg InsertLocationPointParams) error {
	_, err := q.db.Exec(ctx, insertLocationPoint,
		arg.VehicleID,
		arg.TripID,
		arg.Latitude,
		arg.Longitude,
		arg.Bearing,
		arg.Speed,
		arg.Accuracy,
		arg.Timestamp,
		arg.DriverID,
	)
	return err
}

const isTokenRevoked = `-- name: IsTokenRevoked :one
SELECT EXISTS(SELECT 1 FROM revoked_tokens WHERE jti = $1)
`

func (q *Queries) IsTokenRevoked(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenRevoked, jti)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveTripsByVehicle = `-- name: ListActiveTripsByVehicle :many
SELECT DISTINCT ON (t.vehicle_id)
       t.vehicle_id, t.id, t.route_id, t.gtfs_trip_id, t.user_id, u.name AS driver_name
FROM trips t
JOIN users u ON u.id = t.user_id
WHERE t.status = 'active'
ORDER BY t.vehicle_id, t.start_time DESC
`

type ListActiveTripsByVehicleRow struct {
	VehicleID  string
	ID         int64
	RouteID    string
	GtfsTripID string
	UserID     int64
	DriverName string
}

// Schema guarantees one active trip per USER, not per vehicle; newest active
// trip per vehicle is the defined tiebreak (spec §4.8).
func (q *Queries) ListActiveTripsByVehicle(ctx context.Context) ([]ListActiveTripsByVehicleRow, error) {
	rows, err := q.db.Query(ctx, listActiveTripsByVehicle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTripsByVehicleRow
	for rows.Next() {
		var i ListActiveTripsByVehicleRow
		if err := rows.Scan(
			&i.VehicleID,
			&i.ID,
			&i.RouteID,
			&i.GtfsTripID,
			&i.UserID,
			&i.DriverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveVehiclesByUser = `-- name: ListActiveVehiclesByUser :many
SELECT v.id, v.label, v.agency_tag, v.active, v.created_at, v.updated_at
FROM vehicles v
JOIN user_vehicles uv ON uv.vehicle_id = v.id
WHERE uv.user_id = $1 AND v.active = TRUE
ORDER BY v.label, v.id
LIMIT 1000
`

type ListActiveVehiclesByUserRow struct {
	ID        string
	Label     string
	AgencyTag string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Driver-facing: active vehicles assigned to a user. LIMIT is a safety bound, not pagination.
func (q *Queries) ListActiveVehiclesByUser(ctx context.Context, userID int64) ([]ListActiveVehiclesByUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveVehiclesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveVehiclesByUserRow
	for rows.Next() {
		var i ListActiveVehiclesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.AgencyTag,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripLocations = `-- name: ListTripLocations :many
SELECT lp.latitude, lp.longitude, lp.bearing, lp.speed, lp.accuracy,
       lp.timestamp, lp.trip_id, lp.received_at
FROM location_points lp
JOIN trips t ON t.id = $1
WHERE lp.vehicle_id = t.vehicle_id
  AND lp.driver_id = t.user_id::text
  AND lp.received_at >= t.start_time
  AND lp.received_at <= COALESCE(t.end_time, NOW())
ORDER BY lp.received_at ASC
LIMIT 10000
`

type ListTripLocationsRow struct {
	Latitude   float64
	Longitude  float64
	Bearing    pgtype.Float8
	Speed      pgtype.Float8
	Accuracy   pgtype.Float8
	Timestamp  int64
	TripID     string
	ReceivedAt pgtype.Timestamptz
}

// Trail derivation per spec §4.5: location_points.trip_id is a client string,
// not trips.id, so trail points are matched by vehicle + driver + time window.
func (q *Queries) ListTripLocations(ctx context.Context, id int64) ([]ListTripLocationsRow, error) {
	rows, err := q.db.Query(ctx, listTripLocations, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripLocationsRow
	for rows.Next() {
		var i ListTripLocationsRow
		if err := rows.Scan(
			&i.Latitude,
			&i.Longitude,
			&i.Bearing,
			&i.Speed,
			&i.Accuracy,
			&i.Timestamp,
			&i.TripID,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, role, active, created_at, updated_at
FROM users
ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID        int64
	Name      string
	Email     string
	Role      string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByVehicle = `-- name: ListUsersByVehicle :many
SELECT user_id, vehicle_id, created_at
FROM user_vehicles
WHERE vehicle_id = $1
ORDER BY created_at DESC
LIMIT 1000
`

// safety bound; not pagination
func (q *Queries) ListUsersByVehicle(ctx context.Context, vehicleID string) ([]UserVehicle, error) {
	rows, err := q.db.Query(ctx, listUsersByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserVehicle
	for rows.Next() {
		var i UserVehicle
		if err := rows.Scan(&i.UserID, &i.VehicleID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicles = `-- name: ListVehicles :many
SELECT id, label, agency_tag, active, created_at, updated_at
FROM vehicles
ORDER BY created_at DESC
`

type ListVehiclesRow struct {
	ID        string
	Label     string
	AgencyTag string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListVehicles(ctx context.Context) ([]ListVehiclesRow, error) {
	rows, err := q.db.Query(ctx, listVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehiclesRow
	for rows.Next() {
		var i ListVehiclesRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.AgencyTag,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesByUser = `-- name: ListVehiclesByUser :many
SELECT user_id, vehicle_id, created_at
FROM user_vehicles
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1000
`

// safety bound; not pagination
func (q *Queries) ListVehiclesByUser(ctx context.Context, userID int64) ([]UserVehicle, error) {
	rows, err := q.db.Query(ctx, listVehiclesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserVehicle
	for rows.Next() {
		var i UserVehicle
		if err := rows.Scan(&i.UserID, &i.VehicleID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeToken = `-- name: RevokeToken :exec
INSERT INTO revoked_tokens (jti, user_id, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (jti) DO NOTHING
`

type RevokeTokenParams struct {
	Jti       string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

// Idempotent: logging out twice must not error.
func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.Exec(ctx, revokeToken, arg.Jti, arg.UserID, arg.ExpiresAt)
	return err
}

const setUserActive = `-- name: SetUserActive :execrows
UPDATE users SET active = $2 WHERE id = $1
`

type SetUserActiveParams struct {
	ID     int64
	Active bool
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserActive, arg.ID, arg.Active)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setVehicleActive = `-- name: SetVehicleActive :execrows
UPDATE vehicles SET active = $2, updated_at = NOW() WHERE id = $1
`

type SetVehicleActiveParams struct {
	ID     string
	Active bool
}

func (q *Queries) SetVehicleActive(ctx context.Context, arg SetVehicleActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVehicleActive, arg.ID, arg.Active)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startTrip = `-- name: StartTrip :one
INSERT INTO trips (user_id, vehicle_id, route_id, gtfs_trip_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, vehicle_id, route_id, gtfs_trip_id, start_time, end_time, status, created_at, updated_at
`

type StartTripParams struct {
	UserID     int64
	VehicleID  string
	RouteID    string
	GtfsTripID string
}

func (q *Queries) StartTrip(ctx context.Context, arg StartTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, startTrip,
		arg.UserID,
		arg.VehicleID,
		arg.RouteID,
		arg.GtfsTripID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VehicleID,
		&i.RouteID,
		&i.GtfsTripID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unassignUserVehicle = `-- name: UnassignUserVehicle :execrows
DELETE FROM user_vehicles
WHERE user_id = $1 AND vehicle_id = $2
`

type UnassignUserVehicleParams struct {
	UserID    int64
	VehicleID string
}

func (q *Queries) UnassignUserVehicle(ctx context.Context, arg UnassignUserVehicleParams) (int64, error) {
	result, err := q.db.Exec(ctx, unassignUserVehicle, arg.UserID, arg.VehicleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $1, email = $2, role = $3
WHERE id = $4
RETURNING id, name, email, role, active, created_at, updated_at
`

type UpdateUserParams struct {
	Name  string
	Email string
	Role  string
	ID    int64
}

type UpdateUserRow struct {
	ID        int64
	Name      string
	Email     string
	Role      string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// updated_at is maintained by the set_users_updated_at trigger.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVehicleInfo = `-- name: UpdateVehicleInfo :execrows
UPDATE vehicles SET label = $2, agency_tag = $3, updated_at = NOW() WHERE id = $1
`

type UpdateVehicleInfoParams struct {
	ID        string
	Label     string
	AgencyTag string
}

func (q *Queries) UpdateVehicleInfo(ctx context.Context, arg UpdateVehicleInfoParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVehicleInfo, arg.ID, arg.Label, arg.AgencyTag)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAdminVehicle = `-- name: UpsertAdminVehicle :one
INSERT INTO vehicles (id, label, agency_tag)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET label = EXCLUDED.label, agency_tag = EXCLUDED.agency_tag, active = true, updated_at = NOW()
RETURNING id, label, agency_tag, active, created_at, updated_at
`

type UpsertAdminVehicleParams struct {
	ID        string
	Label     string
	AgencyTag string
}

type UpsertAdminVehicleRow struct {
	ID        string
	Label     string
	AgencyTag string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertAdminVehicle(ctx context.Context, arg UpsertAdminVehicleParams) (UpsertAdminVehicleRow, error) {
	row := q.db.QueryRow(ctx, upsertAdminVehicle, arg.ID, arg.Label, arg.AgencyTag)
	var i UpsertAdminVehicleRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.AgencyTag,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertVehicle = `-- name: UpsertVehicle :exec
INSERT INTO vehicles (id)
VALUES ($1)
ON CONFLICT (id) DO UPDATE SET updated_at = NOW()
`

func (q *Queries) UpsertVehicle(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, upsertVehicle, id)
	return err
}

const vehicleExists = `-- name: VehicleExists :one
SELECT EXISTS(SELECT 1 FROM vehicles WHERE id = $1)
`

func (q *Queries) VehicleExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, vehicleExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
